id: opecha:P000306
initial_creation_type: ocr
source_metadata:
  id: bdr:W23435
  title: སྒྲུབ་བརྒྱུད་ཀརྨ་ཀཾ་ཚང་བརྒྱུད་པ་རིན་པོ་ཆེའི་རྣམ་པར་ཐར་པ་རབ་བྱམས་ནོར་བུ་ཟླ་བ་ཆུ་ཤེལ་གྱི་ཕྲེང་བ
  volume: ''
  author: ''
