id: P000306
initial_creation_type: ocr
source_metadata:
  id: bdr:W23435
  title: སྒྲུབ་བརྒྱུད་ཀརྨ་ཀཾ་ཚང་བརྒྱུད་པ་རིན་པོ་ཆེའི་རྣམ་པར་ཐར་པ་རབ་བྱམས་ནོར་བུ་ཟླ་བ་ཆུ་ཤེལ་གྱི་ཕྲེང་བ
  author: ''
  volumes:
    41d084dcd6284ecc87a267bf3bcc96f5:
      image_group_id: I1691
      title: ''
      volume_number: 1
      total_pages: 690
      base_file: v001.txt
    f3fad3ac1110429c9ba0847acffda4ca:
      image_group_id: I1692
      title: ''
      volume_number: 2
      total_pages: 706
      base_file: v002.txt
ebook_metadata:
  title: སྒྲུབ་བརྒྱུད་ཀརྨ་ཀཾ་ཚང་བརྒྱུད་པ་རིན་པོ་ཆེའི་རྣམ་པར་ཐར་པ་རབ་བྱམས་ནོར་བུ་ཟླ་བ་ཆུ་ཤེལ་གྱི་ཕྲེང་བ
  author: ''
  sku: P000306
  cover: cover.jpg
  layers:
  - pagination
